# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOrYlbxadldJD3KZTr73D2nELaQaV18y
"""

def range_1():
    for numero in range(2,-5,-1):
        print(numero, end=", ")
if __name__ == "__main__":
    range_1()