# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PteYKtWaSAxFvch_k6-I903SpKWgPSzs
"""

def retorna_upper_case():
  palavra = input("Digite alguma coisa.: ")


  print(palavra.upper())


if __name__=="__main__":
  retorna_upper_case()

def valida_senha():
  lista_numero = "0123456789"
  lista_caractere_especiais = "!@#$%¨&*()_+"

  senha_digitada = str(input("Digite sua senha....: "))

  tem_numero = False
  tem_caractere_especial = False

  print(senha_digitada)

  for caracter in senha_digitada:
    if caracter in lista_numero:
       tem_numero = True
       break
    else:
      tem_numero = False 

  for caractere in senha_digitada:
    if caractere in lista_caractere_especiais:
      tem_caractere_especiais = True
      break
    else: 
      tem_caractere_especiais = True

    if tem_caractere_especial == True and tem_numero == True:
      print("Senha válida")
    else:
      print("Senha INVALIDA!")

if __name__ == "__main__":
  valida_senha()

class Pessoa:
  def __init__(self, nome):
    self.nome_pessoa = nome

class Equipamentos:
  def __init__(self, nome, tempo_locacao):
    self.nome_equipamento = nome
    self.tempo_locacao = tempo_locacao

from datetime import datetime, timedelta

class Emprestimo:
  def __init__(self, pessoa, equipamento, dias):
    self.pessoa = pessoa
    self.equipamento = equipamento

    if(dias):
       d = datetime.today() + timedelta(dias)
       self.data_devolucao = d
    else:
      d = datetime.today() + timedelta(equipamento.tempo_locacao)
      self.data_devolucao = d

  def to_string(self):
    print(f"A pessoa {self.pessoa} alugou o equipamento: {self.equipamento}e deverá devolver no dia {self.data_devolucao}")

equipamentos = []

equipamentos.append(Equipamentos("Lança foguete", 30))
equipamentos.append(Equipamentos("M1 Abrans" , 60))
equipamentos.append(Equipamentos("Litte Bird", 10))

douglas = Pessoa("Douglas")
geri = Pessoa("Xéri Natalio Tutra")
anderson = Pessoa("Andinho")

emprestimo = []

emprestimo.append(Emprestimo(douglas.nome_pessoa, equipamentos[1],100))
emprestimo.append(Emprestimo(geri.nome_pessoa, equipamentos[2],365))

for emprestimo in empretimo:
  emprestimo.to_string()